FROM docker.elastic.co/elasticsearch/elasticsearch:8.14.3

RUN bin/elasticsearch-plugin install --batch \
  "https://github.com/o19s/elasticsearch-learning-to-rank/releases/download/v1.5.9-es8.14.3/ltr-plugin-v1.5.9-es8.14.3.zip"
